site_name: 批《太平广记》
repo_url: https://github.com/Sharp-Enrich/taiping-guangji
edit_uri: edit/master/docs/
site_url: https://taiping-guangji.readthedocs.io
site_description: 太平广记
site_author: Tacey Wong
copyright: ©2024 Tacey Wong
docs_dir: docs
nav:
  - 前言: 
    - 序: 000_1.md
    - 表: 000_2.md
    - 引用书目: 000_3.md
  - 神仙:
    - 卷第一　神仙一 : 001.md  
    - 卷第二　神仙二 : 002.md
    - 卷第三　神仙三 : 003.md
    - 卷第四　神仙四 : 004.md
    - 卷第五　神仙五 : 005.md
    - 卷第六　神仙六 : 006.md
    - 卷第七　神仙七 : 007.md
    - 卷第八　神仙八 : 008.md
    - 卷第九　神仙九 : 009.md
    - 卷第十　神仙十 : 010.md
    - 卷第十一　神仙十一 : 011.md
    - 卷第十二　神仙十二 : 012.md
    - 卷第十三　神仙十三 : 013.md
    - 卷第十四　神仙十四 : 014.md
    - 卷第十五　神仙十五 : 015.md
    - 卷第十六　神仙十六 : 016.md
    - 卷第十七　神仙十七 : 017.md
    - 卷第十八　神仙十八 : 018.md
    - 卷第十九　神仙十九 : 019.md
    - 卷第二十　神仙二十 : 020.md
    - 卷第二十一　神仙二十一 : 021.md
    - 卷第二十二　神仙二十二 : 022.md
    - 卷第二十三　神仙二十三 : 023.md
    - 卷第二十四　神仙二十四 : 024.md
    - 卷第二十五　神仙二十五 : 025.md
    - 卷第二十六　神仙二十六 : 026.md
    - 卷第二十七　神仙二十七 : 027.md
    - 卷第二十八　神仙二十八 : 028.md
    - 卷第二十九　神仙二十九 : 029.md
    - 卷第三十　神仙三十 : 030.md
    - 卷第三十一　神仙三十一 : 031.md
    - 卷第三十二　神仙三十二 : 032.md
    - 卷第三十三　神仙三十三 : 033.md
    - 卷第三十四　神仙三十四 : 034.md
    - 卷第三十五　神仙三十五 : 035.md
    - 卷第三十六　神仙三十六 : 036.md
    - 卷第三十七　神仙三十七 : 037.md
    - 卷第三十八　神仙三十八 : 038.md
    - 卷第三十九　神仙三十九 : 039.md
    - 卷第四十　神仙四十 : 040.md
    - 卷第四十一　神仙四十一 : 041.md
    - 卷第四十二　神仙四十二 : 042.md
    - 卷第四十三　神仙四十三 : 043.md
    - 卷第四十四　神仙四十四 : 044.md
    - 卷第四十五　神仙四十五 : 045.md
    - 卷第四十六　神仙四十六 : 046.md
    - 卷第四十七　神仙四十七 : 047.md
    - 卷第四十八　神仙四十八 : 048.md
    - 卷第四十九　神仙四十九 : 049.md
    - 卷第五十　神仙五十 : 050.md
    - 卷第五十一　神仙五十一 : 051.md
    - 卷第五十二　神仙五十二 : 052.md
    - 卷第五十三　神仙五十三 : 053.md
    - 卷第五十四　神仙五十四 : 054.md
    - 卷第五十五　神仙五十五 : 055.md
  - 女仙:
    - 卷第五十六　女仙一 : 056.md
    - 卷第五十七　女仙二 : 057.md
    - 卷第五十八　女仙三 : 058.md
    - 卷第五十九　女仙四 : 059.md
    - 卷第六十　女仙五 : 060.md
    - 卷第六十一　女仙六 : 061.md
    - 卷第六十二　女仙七 : 062.md
    - 卷第六十三　女仙八 : 063.md
    - 卷第六十四　女仙九 : 064.md
    - 卷第六十五　女仙十 : 065.md
    - 卷第六十六　女仙十一 : 066.md
    - 卷第六十七　女仙十二 : 067.md
    - 卷第六十八　女仙十三 : 068.md
    - 卷第六十九　女仙十四 : 069.md
    - 卷第七十　女仙十五 : 070.md
  - 道术:
    - 卷第七十一　道术一 : 001.md
    - 卷第七十二　道术二 : 001.md
    - 卷第七十三　道术三 : 001.md
    - 卷第七十四　道术四 : 001.md
    - 卷第七十五　道术五 : 001.md
  - 方士:
    - 卷第七十六　方士一 : 001.md
    - 卷第七十七　方士二 : 001.md
    - 卷第七十八　方士三 : 001.md
    - 卷第七十九　方士四 : 001.md
    - 卷第八十　方士五 : 001.md
  - 异人:
    - 卷第八十一　异人一 : 001.md
    - 卷第八十二　异人二 : 001.md
    - 卷第八十三　异人三 : 001.md
    - 卷第八十四　异人四 : 001.md
    - 卷第八十五　异人五 : 001.md
    - 卷第八十六　异人六 : 001.md
  - 异僧:
    - 卷第八十七　异僧一 : 001.md
    - 卷第八十八　异僧二 : 001.md
    - 卷第八十九　异僧三 : 001.md
    - 卷第九十　异僧四 : 001.md
    - 卷第九十一　异僧五 : 001.md
    - 卷第九十二　异僧六 : 001.md
    - 卷第九十三　异僧七 : 001.md
    - 卷第九十四　异僧八 : 001.md
    - 卷第九十五　异僧九 : 001.md
    - 卷第九十六　异僧十 : 001.md
    - 卷第九十七　异僧十一 : 001.md
    - 卷第九十八　异僧十二 : 001.md
  - 释证:
    - 卷第九十九　释证一 : 001.md
    - 卷第一百　释证二 : 001.md
    - 卷第一百一　释证三 : 001.md
  - 报应:
    - 卷第一百二　报应一（金刚经） : 001.md
    - 卷第一百三　报应二（金刚经） : 001.md
    - 卷第一百四　报应三（金刚经） : 001.md
    - 卷第一百五　报应四（金刚经） : 001.md
    - 卷第一百六　报应五（金刚经） : 001.md
    - 卷第一百七　报应六（金刚经） : 001.md
    - 卷第一百八　报应七（金刚经） : 001.md
    - 卷第一百九　报应八（法华经） : 001.md
    - 卷第一百一十　报应九（观音经） : 001.md
    - 卷第一百一十一　报应十（观音经） : 001.md
    - 卷第一百一十二　报应十一（崇经像） : 001.md
    - 卷第一百一十三　报应十二（崇经像） : 001.md
    - 卷第一百一十四　报应十三（崇经像） : 001.md
    - 卷第一百一十五　报应十四（崇经像） : 001.md
    - 卷第一百一十六　报应十五（崇经像） : 001.md
    - 卷第一百一十七　报应十六（阴德） : 001.md
    - 卷第一百一十八　报应十七（异类） : 001.md
    - 卷第一百一十九　报应十八（冤报） : 001.md
    - 卷第一百二十　报应十九（冤报） : 001.md
    - 卷第一百二十一　报应二十（冤报） : 001.md
    - 卷第一百二十二　报应二十一（冤报） : 001.md
    - 卷第一百二十三　报应二十二（冤报） : 001.md
    - 卷第一百二十四　报应二十三（冤报） : 001.md
    - 卷第一百二十五　报应二十四（冤报） : 001.md
    - 卷第一百二十六　报应二十五 : 001.md
    - 卷第一百二十七　报应二十六 : 001.md
    - 卷第一百二十八　报应二十七 : 001.md
    - 卷第一百二十九　报应二十八（婢妾） : 001.md
    - 卷第一百三十　报应二十九（婢妾） : 001.md
    - 卷第一百三十一　报应三十（杀生） : 001.md
    - 卷第一百三十二　报应三十一（杀生） : 001.md
    - 卷第一百三十三　报应三十二（杀生） : 001.md
    - 卷第一百三十四　报应三十三（宿业畜生） : 001.md
  - 征应:
    - 卷第一百三十五　征应一（帝王休征） : 001.md
    - 卷第一百三十六　征应二（帝王休征） : 001.md
    - 卷第一百三十七　征应三（人臣休征） : 001.md
    - 卷第一百三十八　征应四（人臣休征） : 001.md
    - 卷第一百三十九　征应五（邦国咎征） : 001.md
    - 卷第一百四十　征应六（邦国咎征） : 001.md
    - 卷第一百四十一　征应七（人臣咎征） : 001.md
    - 卷第一百四十二　征应八（人臣咎征） : 001.md
    - 卷第一百四十三　征应九（人臣咎征） : 001.md
    - 卷第一百四十四　征应十（人臣咎征） : 001.md
    - 卷第一百四十五　征应十一（人臣咎征） : 001.md
  - 定数:
    - 卷第一百四十六　定数一 : 001.md
    - 卷第一百四十七　定数二 : 001.md
    - 卷第一百四十八　定数三 : 001.md
    - 卷第一百四十九　定数四 : 001.md
    - 卷第一百五十　定数五 : 001.md
    - 卷第一百五十一　定数六 : 001.md
    - 卷第一百五十二　定数七 : 001.md
    - 卷第一百五十三　定数八 : 001.md
    - 卷第一百五十四　定数九 : 001.md
    - 卷第一百五十五　定数十 : 001.md
    - 卷第一百五十六　定数十一 : 001.md
    - 卷第一百五十七　定数十二 : 001.md
    - 卷第一百五十八　定数十三 : 001.md
    - 卷第一百五十九　定数十四（婚姻） : 001.md
    - 卷第一百六十　定数十五（婚姻） : 001.md
  - 感应:
    - 卷第一百六十一　感应一 : 001.md
    - 卷第一百六十二　感应二 : 001.md
  - 谶应:
    - 卷第一百六十三　谶应 : 001.md
  - 名贤:
    - 卷第一百六十四　名贤（讽谏附） : 001.md
  - 廉俭:
    - 卷第一百六十五　廉俭（吝啬附） : 001.md
  - 气义:
    - 卷第一百六十六　气义一 : 001.md
    - 卷第一百六十七　气义二 : 001.md
    - 卷第一百六十八　气义三 : 001.md
  - 知人:
    - 卷第一百六十九　知人一 : 001.md
    - 卷第一百七十　知人二 : 001.md
  - 精察:
    - 卷第一百七十一　精察一 : 001.md
    - 卷第一百七十二　精察二 : 001.md
  - 俊辩:
    - 卷第一百七十三　俊辩一 : 001.md
    - 卷第一百七十四　俊辩二（幼敏附） : 001.md
  - 幼敏:
    - 卷第一百七十五　幼敏 : 001.md
  - 器量:
    - 卷第一百七十六　器量一 : 001.md
    - 卷第一百七十七　器量二 : 001.md
  - 贡举:
    - 卷第一百七十八　贡举一 : 001.md
    - 卷第一百七十九　贡举二 : 001.md
    - 卷第一百八十　贡举三 : 001.md
    - 卷第一百八十一　贡举四 : 001.md
    - 卷第一百八十二　贡举五 : 001.md
    - 卷第一百八十三　贡举六 : 001.md
    - 卷第一百八十四　贡举七（代族附） : 001.md
  - 铨选:
    - 卷第一百八十五　铨选一 : 001.md
    - 卷第一百八十六　铨选二 : 001.md
  - 职官:
    - 卷第一百八十七　职官 : 001.md
  - 权倖:
    - 卷第一百八十八　权倖 : 001.md
  - 将帅:
    - 卷第一百八十九　将帅一 : 001.md
    - 卷第一百九十　将帅二（杂谲智附） : 001.md
  - 骁勇:
    - 卷第一百九十一　骁勇一 : 001.md
    - 卷第一百九十二　骁勇二 : 001.md
  - 豪侠:  
    - 卷第一百九十三　豪侠一 : 001.md
    - 卷第一百九十四　豪侠二 : 001.md
    - 卷第一百九十五　豪侠三 : 001.md
    - 卷第一百九十六　豪侠四 : 001.md
  - 博物:
    - 卷第一百九十七　博物 : 001.md
  - 文章:  
    - 卷第一百九十八　文章一 : 001.md
    - 卷第一百九十九　文章二 : 001.md
    - 卷第二百　　文章三 : 001.md
  - 才名:  
    - 卷第二百一　才名（好尚附） : 001.md
  - 儒行:  
    - 卷第二百二　儒行（怜才　高逸） : 001.md
  - 乐:  
    - 卷第二百三　　乐一 : 001.md
    - 卷第二百四　　乐二 : 001.md
    - 卷第二百五　乐三 : 001.md
  - 书:
    - 卷第二百六　　书一 : 001.md
    - 卷第二百七　　书二 : 001.md
    - 卷第二百八　书三 : 001.md
    - 卷第二百九　书四 : 001.md
  - 画:
    - 卷第二百十　画一 : 001.md
    - 卷第二百十一　画二 : 001.md
    - 卷第二百十二　画三 : 001.md
    - 卷第二百十三　画四 : 001.md
    - 卷第二百十四　　画五 : 001.md
  - 算术:
    - 卷第二百十五　　算术 : 001.md
  - 卜筮:
    - 卷第二百十六　　卜筮一 : 001.md
    - 卷第二百十七　卜筮二 : 001.md
  - 医:
    - 卷第二百十八　医一 : 001.md
    - 卷第二百十九　医二 : 001.md
    - 卷第二百二十　　医三 : 001.md
  - 相:
    - 卷第二百二十一　　相一 : 001.md
    - 卷第二百二十二　　相二 : 001.md
    - 卷第二百二十三　相三 : 001.md
    - 卷第二百二十四　相四 : 001.md
  - 伎巧:
    - 卷第二百二十五　伎巧一 : 001.md
    - 卷第二百二十六　伎巧二 : 001.md
    - 卷第二百二十七　伎巧三（绝艺附） : 001.md
  - 博戏:  
    - 卷第二百二十八　博戏 : 001.md
  - 器玩:
    - 卷第二百二十九　　器玩一 : 001.md
    - 卷第二百三十　器玩二 : 001.md
    - 卷第二百三十一　　器玩三 : 001.md
    - 卷第二百三十二　　器玩四 : 001.md
  - 酒:
    - 卷第二百三十三　　酒（酒量、嗜酒附） : 001.md
  - 食:
    - 卷第二百三十四　　食（能食、菲食附） : 001.md
  - 交友:
    - 卷第二百三十五　　交友 : 001.md
  - 奢侈:
    - 卷第二百三十六　　奢侈一 : 001.md
    - 卷第二百三十七　　奢侈二 : 001.md
  - 诡诈:
    - 卷第二百三十八　　诡诈 : 001.md
  - 谄佞:
    - 卷第二百三十九　　谄佞一 : 001.md
    - 卷第二百四十　　谄佞二 : 001.md
    - 卷第二百四十一　谄佞三 : 001.md
  - 谬误:
    - 卷第二百四十二　　谬误（遗忘附） : 001.md
  - 治生:
    - 卷第二百四十三　　治生（贪附） : 001.md
  - 褊急:
    - 卷第二百四十四　　褊急 : 001.md
  - 诙谐:
    - 卷第二百四十五　　诙谐一 : 001.md
    - 卷第二百四十六　　诙谐二 : 001.md
    - 卷第二百四十七　　诙谐三 : 001.md
    - 卷第二百四十八　　诙谐四 : 001.md
    - 卷第二百四十九　　诙谐五 : 001.md
    - 卷第二百五十　　诙谐六 : 001.md
    - 卷第二百五十一　　诙谐七 : 001.md
    - 卷第二百五十二　　诙谐八 : 001.md
  - 嘲诮:
    - 卷第二百五十三　　嘲诮一 : 001.md
    - 卷第二百五十四　　嘲诮二 : 001.md
    - 卷第二百五十五　　嘲诮三 : 001.md
    - 卷第二百五十六　　嘲诮四 : 001.md
    - 卷第二百五十七　　嘲诮五 : 001.md
  - 嗤鄙:
    - 卷第二百五十八　　嗤鄙一 : 001.md
    - 卷第二百五十九　　嗤鄙二 : 001.md
    - 卷第二百六十　　嗤鄙三 : 001.md
    - 卷第二百六十一　　嗤鄙四 : 001.md
    - 卷第二百六十二　　嗤鄙五 : 001.md
  - 无赖:
    - 卷第二百六十三　　无赖一 : 001.md
    - 卷第二百六十四　　无赖二 : 001.md
  - 轻薄:
    - 卷第二百六十五　　轻薄一 : 001.md
    - 卷第二百六十六　　轻薄二 : 001.md
  - 酷暴:
    - 卷第二百六十七　　酷暴一 : 001.md
    - 卷第二百六十八　　酷暴二 : 001.md
    - 卷第二百六十九　　酷暴三 : 001.md
  - 妇人:
    - 卷第二百七十　　妇人一 : 001.md
    - 卷第二百七十一　　妇人二 : 001.md
    - 卷第二百七十二　　妇人三 : 001.md
    - 卷第二百七十三　　妇人四（附妓女） : 001.md
  - 情感:
    - 卷第二百七十四　　情感 : 001.md
  - 童仆:
    - 卷第二百七十五　　童仆（奴婢附） : 001.md
  - 梦:
    - 卷第二百七十六　　梦一 : 001.md
    - 卷第二百七十七　　梦二 : 001.md
    - 卷第二百七十八　　梦三 : 001.md
    - 卷第二百七十九　　梦四 : 001.md
    - 卷第二百八十　　梦五（鬼神上） : 001.md
    - 卷第二百八十一　　梦六 : 001.md
    - 卷第二百八十二　　梦七 : 001.md
  - 巫:
    - 卷第二百八十三　　巫（附厌咒） : 001.md
  - 幻术:
    - 卷第二百八十四　　幻术一 : 001.md
    - 卷第二百八十五　　幻术二 : 001.md
    - 卷第二百八十六　　幻术三 : 001.md
    - 卷第二百八十七　　幻术四 : 001.md
  - 妖妄:
    - 卷第二百八十八　　妖妄一 : 001.md
    - 卷第二百八十九　　妖妄二 : 001.md
    - 卷第二百九十　　妖妄三 : 001.md
  - 神:
    - 卷第二百九十一　　神一 : 001.md
    - 卷第二百九十二　　神二 : 001.md
    - 卷第二百九十三　　神三 : 001.md
    - 卷第二百九十四　　神四 : 001.md
    - 卷第二百九十五　　神五 : 001.md
    - 卷第二百九十六　　神六 : 001.md
    - 卷第二百九十七　　神七 : 001.md
    - 卷第二百九十八　　神八 : 001.md
    - 卷第二百九十九　　神九 : 001.md
    - 卷第三百　　神十 : 001.md
    - 卷第三百一　神十一 : 001.md
    - 卷第三百二　神十二 : 001.md
    - 卷第三百三　神十三 : 001.md
    - 卷第三百四　神十四 : 001.md
    - 卷第三百五　神十五 : 001.md
    - 卷第三百六　神十六 : 001.md
    - 卷第三百七　神十七 : 001.md
    - 卷第三百八　神十八 : 001.md
    - 卷第三百九　神十九 : 001.md
    - 卷第三百一十　神二十 : 001.md
    - 卷第三百一十一　神二十一 : 001.md
    - 卷第三百一十二　神二十二 : 001.md
    - 卷第三百一十三　神二十三 : 001.md
    - 卷三百十四　神二十四 : 001.md
    - 卷第三百十五　神二十五（淫祠附） : 001.md
  - 鬼:
    - 卷第三百十六　鬼一 : 001.md
    - 卷第三百十七　鬼二 : 001.md
    - 卷第三百一十八　鬼三 : 001.md
    - 卷第三百一十九　鬼四 : 001.md
    - 卷第三百二十　鬼五 : 001.md
    - 卷第三百二十一　鬼六 : 001.md
    - 卷第三百二十二　鬼七 : 001.md
    - 卷第三百二十三　鬼八 : 001.md
    - 卷第三百二十四　鬼九 : 001.md
    - 卷第三百二十五　鬼十 : 001.md
    - 卷第三百二十六　　鬼十一 : 001.md
    - 卷第三百二十七　　鬼十二 : 001.md
    - 卷第三百二十八　　鬼十三 : 001.md
    - 卷第三百二十九　　鬼十四 : 001.md
    - 卷第三百三十　　鬼十五 : 001.md
    - 卷第三百三十一　　鬼十六 : 001.md
    - 卷第三百三十二　　鬼十七 : 001.md
    - 卷第三百三十三　　鬼十八 : 001.md
    - 卷第三百三十四　　鬼十九 : 001.md
    - 卷第三百三十五　　鬼二十 : 001.md
    - 卷第三百三十六　鬼二十一 : 001.md
    - 卷第三百三十七　鬼二十二 : 001.md
    - 卷第三百三十八　鬼二十三 : 001.md
    - 卷第三百三十九　鬼二十四 : 001.md
    - 卷第三百四十　　鬼二十五 : 001.md
    - 卷第三百四十一　鬼二十六 : 001.md
    - 卷第三百四十二　鬼二十七 : 001.md
    - 卷第三百四十三　鬼二十八 : 001.md
    - 卷第三百四十四　鬼二十九 : 001.md
    - 卷第三百四十五　　鬼三十 : 001.md
    - 卷第三百四十六　鬼三十一 : 001.md
    - 卷第三百四十七　鬼三十二 : 001.md
    - 卷第三百四十八　鬼三十三 : 001.md
    - 卷第三百四十九　鬼三十四 : 001.md
    - 卷第三百五十　　鬼三十五 : 001.md
    - 卷第三百五十一　鬼三十六 : 001.md
    - 卷第三百五十二　鬼三十七 : 001.md
    - 卷第三百五十三　鬼三十八 : 001.md
    - 卷第三百五十四　 鬼三十九 : 001.md
    - 卷第三百五十五　　鬼四十 : 001.md
  - 夜叉:
    - 卷第三百五十六　　夜叉一 : 001.md
    - 卷第三百五十七　　夜叉二 : 001.md
  - 神魂:  
    - 卷第三百五十八　　神魂一 : 001.md
  - 妖怪:  
    - 卷第三百五十九　　妖怪一 : 001.md
    - 卷第三百六十　　妖怪二 : 001.md
    - 卷第三百六十一　　妖怪三 : 001.md
    - 卷第三百六十二　　妖怪四 : 001.md
    - 卷第三百六十三　　妖怪五 : 001.md
    - 卷第三百六十四　　妖怪六 : 001.md
    - 卷第三百六十五　　妖怪七 : 001.md
    - 卷第三百六十六　　妖怪八 : 001.md
    - 卷第三百六十七　　妖怪九（人妖附） : 001.md
  - 精怪:  
    - 卷第三百六十八　　精怪一 : 001.md
    - 卷第三百六十九　　精怪二 : 001.md
    - 卷第三百七十　　精怪三 : 001.md
    - 卷第三百七十一　　精怪四 : 001.md
    - 卷第三百七十二　　精怪五 : 001.md
    - 卷第三百七十三　　精怪六 : 001.md
  - 灵异:  
    - 卷第三百七十四　　灵异 : 001.md
  - 再生:
    - 卷第三百七十五　　再生一 : 001.md
    - 卷第三百七十六　　再生二 : 001.md
    - 卷第三百七十七　　再生三 : 001.md
    - 卷第三百七十八　　再生四 : 001.md
    - 卷第三百七十九　　再生五 : 001.md
    - 卷第三百八十　　再生六 : 001.md
    - 卷第三百八十一　　再生七 : 001.md
    - 卷第三百八十二　　再生八 : 001.md
    - 卷第三百八十三　　再生九 : 001.md
    - 卷第三百八十四　　再生十 : 001.md
    - 卷第三百八十五　再生十一 : 001.md
    - 卷第三百八十六　再生十二 : 001.md
  - 悟前生:  
    - 卷第三百八十七　悟前生一 : 001.md
    - 卷第三百八十八　悟前生二 : 001.md
  - 冢墓:
    - 卷第三百八十九　　冢墓一 : 001.md
    - 卷第三百九十　　冢墓二 : 001.md
  - 铭记:
    - 卷第三百九十一　　铭记一 : 001.md
    - 卷第三百九十二　　铭记二 : 001.md
  - 雷:
    - 卷第三百九十三　　雷一 : 001.md
    - 卷第三百九十四　　雷二 : 001.md
    - 卷第三百九十五　　雷三 : 001.md
  - 风:
    - 卷第三百九十六　雨（风虹附） : 001.md
  - 山:
    - 卷第三百九十七　　山（溪附） : 001.md
  - 石头:
    - 卷第三百九十八　　石（坡沙附） : 001.md
  - 水:
    - 卷第三百九十九　　水（井附） : 001.md
  - 宝:
    - 卷第四百　　宝一 : 001.md
    - 卷第四百一　　宝二（金玉附） : 001.md
    - 卷第四百二　　宝三 : 001.md
    - 卷第四百三　　宝四（杂宝上） : 001.md
    - 卷第四百四　　宝五（杂宝下） : 001.md
    - 卷第四百五　　宝六（钱、奇物附） : 001.md
  - 草木:
    - 卷第四百六　　草木一（文理木附） : 001.md
    - 卷第四百七　　草木二 : 001.md
    - 卷第四百八　　草木三 : 001.md
    - 卷第四百九　　草木四 : 001.md
    - 卷第四百一十　　草木五 : 001.md
    - 卷第四百一十一　　草木六 : 001.md
    - 卷第四百十二　　草木七（五谷、茶、荈附） : 001.md
    - 卷第四百十三　　草木八 : 001.md
    - 卷第四百十四　　草木九 : 001.md
    - 卷第四百一十五　　草木十 : 001.md
    - 卷第四百十六　　草木十一 : 001.md
    - 卷第四百一十七　　草木十二 : 001.md
  - 龙:
    - 卷第四百一十八　　龙一 : 001.md
    - 卷第四百一十九　　龙二 : 001.md
    - 卷第四百二十　　龙三 : 001.md
    - 卷第四百二十一　　龙四 : 001.md
    - 卷第四百二十二　　龙五 : 001.md
    - 卷第四百二十三　　龙六 : 001.md
    - 卷第四百二十四　　龙七 : 001.md
    - 卷第四百二十五　龙八 : 001.md
  - 虎:
    - 卷第四百二十六　虎一 : 001.md
    - 卷第四百二十七　虎二 : 001.md
    - 卷第四百二十八　虎三 : 001.md
    - 卷第四百二十九　虎四 : 001.md
    - 卷第四百三十　虎五 : 001.md
    - 卷第四百三十一　虎六 : 001.md
    - 卷第四百三十二 虎七 : 001.md
    - 卷第四百三十三 虎八 : 001.md
  - 畜兽:
    - 卷第四百三十四 畜兽一 : 001.md
    - 卷第四百三十五 畜兽二 : 001.md
    - 卷第四百三十六　畜兽三 : 001.md
    - 卷第四百三十七　畜兽四 : 001.md
    - 卷第四百三十八　畜兽五 : 001.md
    - 卷第四百三十九　畜兽六 : 001.md
    - 卷第四百四十　畜兽七 : 001.md
    - 卷第四百四十一　畜兽八 : 001.md
    - 卷第四百四十二　畜兽九 : 001.md
    - 卷第四百四十三　畜兽十 : 001.md
    - 卷第四百四十四　畜兽十一 : 001.md
    - 卷第四百四十五　畜兽十二 : 001.md
    - 卷第四百四十六　畜兽十三 : 001.md
  - 狐:
    - 卷第四百四十七　狐一 : 001.md
    - 卷第四百四十八　狐二 : 001.md
    - 卷第四百四十九　狐三 : 001.md
    - 卷第四百五十　狐四 : 001.md
    - 卷第四百五十一　狐五 : 001.md
    - 卷第四百五十二　狐六 : 001.md
    - 卷第四百五十三　狐七 : 001.md
    - 卷第四百五十四　狐八 : 001.md
    - 卷第四百五十五　狐九 : 001.md
  - 蛇:
    - 卷第四百五十六　蛇一 : 001.md
    - 卷第四百五十七　蛇二 : 001.md
    - 卷第四百五十八　蛇三 : 001.md
    - 卷第四百五十九　蛇四 : 001.md
  - 禽鸟:
    - 卷第四百六十　禽鸟一 : 001.md
    - 卷第四百六十一　禽鸟二 : 001.md
    - 卷第四百六十二　禽鸟三 : 001.md
    - 卷第四百六十三　禽鸟四 : 001.md
  - 水族:
    - 卷第四百六十四　水族一 : 001.md
    - 卷第四百六十五　水族二 : 001.md
    - 卷四百六十六　水族三 : 001.md
    - 卷第四百六十七　水族四 : 001.md
    - 卷第四百六十八　水族五 : 001.md
    - 卷第四百六十九　水族六 : 001.md
    - 卷第四百七十　水族七 : 001.md
    - 卷第四百七十一　水族八 : 001.md
    - 卷第四百七十二　水族九（龟） : 001.md
  - 昆虫:
    - 卷第四百七十三　昆虫一 : 001.md
    - 卷第四百七十四　昆虫二 : 001.md
    - 卷第四百七十五　昆虫三 : 001.md
    - 卷第四百七十六　昆虫四 : 001.md
    - 第四百七十七　昆虫五 : 001.md
    - 第四百七十八　昆虫六 : 001.md
    - 第四百七十九　昆虫七 : 001.md
  - 蛮夷:
    - 第四百八十　蛮夷一 : 001.md
    - 卷第四百八十一　蛮夷二 : 001.md
    - 卷第四百八十二　蛮夷三 : 001.md
    - 卷第四百八十三　蛮夷四 : 001.md
  - 杂传:  
    - 卷第四百八十四　杂传记一 : 001.md
    - 卷第四百八十五　杂传记二 : 001.md
    - 卷第四百八十六　杂传记三 : 001.md
    - 卷第四百八十七　杂传记四 : 001.md
    - 卷第四百八十八　杂传记五 : 001.md
    - 第四百八十九　杂传记六 : 001.md
    - 第四百九十　杂传记七 : 001.md
    - 第四百九十一　杂传记八 : 001.md
    - 卷第四百九十二　杂传记九 : 001.md
  - 杂录:
    - 卷第四百九十三　杂录一 : 001.md
    - 第四百九十四　杂录二 : 001.md
    - 卷第四百九十五　杂录三 : 001.md
    - 卷第四百九十六　杂录四 : 001.md
    - 卷第四百九十七　杂录五 : 001.md
    - 卷第四百九十八　杂录六 : 001.md
    - 卷第四百九十九　杂录七 : 001.md
    - 卷第五百　杂录八  : 001.md

  
theme:
  # logo: logo.png
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - content.code.copy
    - content.code.select

  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至暗色主题
    - scheme: slate 
      primary: black
      toggle:
        icon: material/toggle-switch
        name: 切换至浅色主题

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      encoding: utf-8
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - glightbox
  - search
  # - with-pdf
        #author: WHO
        #copyright: ANY TEXT
        #
        #cover: false
        #back_cover: true
        #cover_title: TITLE TEXT
        #cover_subtitle: SUBTITLE TEXT
        #custom_template_path: TEMPLATES PATH
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        # two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        #output_path: any-place/document.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #show_anchors: true
        #verbose: true 
  # - pdf-export:
  #     verbose: true
  #     combined: true
  #     enabled_if_env: ENABLE_PDF_EXPORT  

# extra:
#   generator: false
#   disqus: golang-cookbook
# https://github.com/zhaoterryy/mkdocs-pdf-export-plugin
# pip install mkdocs-pdf-export-plugin
       